#!/bin/sh /etc/rc.common

# shellcheck disable=SC2034          # consumed by /etc/rc.common
USE_PROCD=1

START=98
STOP=98

start_service()
{
	procd_open_instance
	procd_set_param command /usr/bin/ucode \
		-lstruct -lubus -lbpf -luci -llog -lfs \
		/usr/libexec/obserwrt/obserwrt.uc
	procd_set_param env BPF_OBJ=/usr/lib/obserwrt/obserwrt-bpf.o
	procd_set_param respawn 3600 5 5
	procd_set_param file /etc/config/obserwrt
	procd_set_param stdio /dev/null 1 1
	procd_close_instance
}